all:
	latex doku-10.tex
	dvipdf doku-10.dvi
# 	epspdf codebook0.eps
# 	epspdf codebook1.eps
# 	epspdf codebook2.eps
# 	epspdf codebook3.eps
# 	epspdf codebook4.eps
# 	epspdf codebook5.eps
# 	epspdf codebook6.eps
# 	epspdf codebook7.eps
# 	epspdf codebook8.eps
# 	epspdf codebook9.eps
# 	epspdf codebook10.eps
# 	epspdf codebook11.eps
# 	epspdf codebook12.eps
# 	epspdf codebook13.eps
# 	epspdf codebook14.eps
# 	epspdf codebook15.eps
# 	epspdf codebook16.eps
# 	epspdf codebook17.eps
# 	epspdf codebook18.eps
# 	epspdf codebook19.eps
# 	epspdf codebook20.eps
